package com.becarios.proyecto_definitivo.model.horas_costes;
// Generated 21-abr-2017 13:47:07 by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Valoracionfinal generated by hbm2java
 */
@Entity
@Table(name = "valoracionfinal", catalog = "HE")
public class Valoracionfinal implements java.io.Serializable {

    private ValoracionfinalId id;
    private int horas;
    private double coste;

    public Valoracionfinal() {
    }

    public Valoracionfinal(ValoracionfinalId id, int horas, double coste) {
        this.id = id;
        this.horas = horas;
        this.coste = coste;
    }

    @EmbeddedId

    @AttributeOverrides({
            @AttributeOverride(name = "idProyecto", column = @Column(name = "idProyecto", nullable = false) ),
            @AttributeOverride(name = "nombre", column = @Column(name = "Nombre", nullable = false, length = 45) ) })
    public ValoracionfinalId getId() {
        return this.id;
    }

    public void setId(ValoracionfinalId id) {
        this.id = id;
    }

    @Column(name = "Horas", nullable = false)
    public int getHoras() {
        return this.horas;
    }

    public void setHoras(int horas) {
        this.horas = horas;
    }

    @Column(name = "Coste", nullable = false)
    public double getCoste() {
        return coste;
    }

    public void setCoste(double coste) {
        this.coste = coste;
    }
}
