package com.becarios.proyecto_definitivo.tablas;
// Generated 21-jul-2017 9:21:12 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Rol generated by hbm2java
 */
@Entity
@Table(name = "rol", catalog = "he")
public class Rol implements java.io.Serializable {

    private int id;
    private String nombre;
    private Set rolHasUsuarios = new HashSet(0);

    public Rol() {
    }

    public Rol(int id, String nombre) {
        this.id = id;
        this.nombre = nombre;
    }

    public Rol(int id, String nombre, Set rolHasUsuarios) {
        this.id = id;
        this.nombre = nombre;
        this.rolHasUsuarios = rolHasUsuarios;
    }

    @Id

    @Column(name = "id", unique = true, nullable = false)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @Column(name = "nombre", nullable = false, length = 45)
    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "rol")
    public Set getRolHasUsuarios() {
        return this.rolHasUsuarios;
    }

    public void setRolHasUsuarios(Set rolHasUsuarios) {
        this.rolHasUsuarios = rolHasUsuarios;
    }

}
