package com.becarios.proyecto_definitivo.tablas;// default package

// Generated 21-jul-2017 9:21:12 by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * RolHasUsuario generated by hbm2java
 */
@Entity
@Table(name = "rol_has_usuario", catalog = "he")
public class RolHasUsuario implements java.io.Serializable {

    private RolHasUsuarioId id;
    private Rol rol;
    private Usuario usuario;

    public RolHasUsuario() {
    }

    public RolHasUsuario(RolHasUsuarioId id, Rol rol, Usuario usuario) {
        this.id = id;
        this.rol = rol;
        this.usuario = usuario;
    }

    @EmbeddedId

    @AttributeOverrides({
            @AttributeOverride(name = "usuarioId", column = @Column(name = "usuario_id", nullable = false) ),
            @AttributeOverride(name = "rolId", column = @Column(name = "rol_id", nullable = false) ) })
    public RolHasUsuarioId getId() {
        return this.id;
    }

    public void setId(RolHasUsuarioId id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "rol_id", nullable = false, insertable = false, updatable = false)
    public Rol getRol() {
        return this.rol;
    }

    public void setRol(Rol rol) {
        this.rol = rol;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "usuario_id", nullable = false, insertable = false, updatable = false)
    public Usuario getUsuario() {
        return this.usuario;
    }

    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

}
