package com.becarios.proyecto_definitivo.tablas;// default package

// Generated 21-jul-2017 9:21:12 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * RolHasUsuarioId generated by hbm2java
 */
@Embeddable
public class RolHasUsuarioId implements java.io.Serializable {

    private int usuarioId;
    private int rolId;

    public RolHasUsuarioId() {
    }

    public RolHasUsuarioId(int usuarioId, int rolId) {
        this.usuarioId = usuarioId;
        this.rolId = rolId;
    }

    @Column(name = "usuario_id", nullable = false)
    public int getUsuarioId() {
        return this.usuarioId;
    }

    public void setUsuarioId(int usuarioId) {
        this.usuarioId = usuarioId;
    }

    @Column(name = "rol_id", nullable = false)
    public int getRolId() {
        return this.rolId;
    }

    public void setRolId(int rolId) {
        this.rolId = rolId;
    }

    public boolean equals(Object other) {
        if ((this == other))
            return true;
        if ((other == null))
            return false;
        if (!(other instanceof RolHasUsuarioId))
            return false;
        RolHasUsuarioId castOther = (RolHasUsuarioId) other;

        return (this.getUsuarioId() == castOther.getUsuarioId()) && (this.getRolId() == castOther.getRolId());
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + this.getUsuarioId();
        result = 37 * result + this.getRolId();
        return result;
    }

}
