package com.becarios.proyecto_definitivo.tablas;// default package

// Generated 21-jul-2017 9:21:12 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name = "usuario", catalog = "he")
public class Usuario implements java.io.Serializable {

    private int id;
    private String nombreUsuario;
    private String nombreCompleto;
    private String hashedPassword;
    private String salt;
    private byte isPasswordChanged;
    private byte isActive;
    private Set usuarioHasProyectos = new HashSet(0);
    private Set rolHasUsuarios = new HashSet(0);

    public Usuario() {
    }

    public Usuario(int id, String nombreUsuario, String nombreCompleto, String hashedPassword, String salt,
            byte isPasswordChanged, byte isActive) {
        this.id = id;
        this.nombreUsuario = nombreUsuario;
        this.nombreCompleto = nombreCompleto;
        this.hashedPassword = hashedPassword;
        this.salt = salt;
        this.isPasswordChanged = isPasswordChanged;
        this.isActive = isActive;
    }

    public Usuario(int id, String nombreUsuario, String nombreCompleto, String hashedPassword, String salt,
            byte isPasswordChanged, byte isActive, Set usuarioHasProyectos, Set rolHasUsuarios) {
        this.id = id;
        this.nombreUsuario = nombreUsuario;
        this.nombreCompleto = nombreCompleto;
        this.hashedPassword = hashedPassword;
        this.salt = salt;
        this.isPasswordChanged = isPasswordChanged;
        this.isActive = isActive;
        this.usuarioHasProyectos = usuarioHasProyectos;
        this.rolHasUsuarios = rolHasUsuarios;
    }

    @Id

    @Column(name = "id", unique = true, nullable = false)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @Column(name = "nombre_usuario", nullable = false, length = 45)
    public String getNombreUsuario() {
        return this.nombreUsuario;
    }

    public void setNombreUsuario(String nombreUsuario) {
        this.nombreUsuario = nombreUsuario;
    }

    @Column(name = "nombre_completo", nullable = false, length = 45)
    public String getNombreCompleto() {
        return this.nombreCompleto;
    }

    public void setNombreCompleto(String nombreCompleto) {
        this.nombreCompleto = nombreCompleto;
    }

    @Column(name = "hashed_password", nullable = false, length = 500)
    public String getHashedPassword() {
        return this.hashedPassword;
    }

    public void setHashedPassword(String hashedPassword) {
        this.hashedPassword = hashedPassword;
    }

    @Column(name = "salt", nullable = false, length = 500)
    public String getSalt() {
        return this.salt;
    }

    public void setSalt(String salt) {
        this.salt = salt;
    }

    @Column(name = "is_password_changed", nullable = false)
    public byte getIsPasswordChanged() {
        return this.isPasswordChanged;
    }

    public void setIsPasswordChanged(byte isPasswordChanged) {
        this.isPasswordChanged = isPasswordChanged;
    }

    @Column(name = "is_active", nullable = false)
    public byte getIsActive() {
        return this.isActive;
    }

    public void setIsActive(byte isActive) {
        this.isActive = isActive;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "usuario")
    public Set getUsuarioHasProyectos() {
        return this.usuarioHasProyectos;
    }

    public void setUsuarioHasProyectos(Set usuarioHasProyectos) {
        this.usuarioHasProyectos = usuarioHasProyectos;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "usuario")
    public Set getRolHasUsuarios() {
        return this.rolHasUsuarios;
    }

    public void setRolHasUsuarios(Set rolHasUsuarios) {
        this.rolHasUsuarios = rolHasUsuarios;
    }

}
